spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: springcloud-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7301/eureka
info:
  app.name: mldn-microcloud-dev-1
  company.name: www.mldn.cn
  app.version: v-dev-1.0.0

---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: springcloud-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7301/eureka
info:
  app.name: mldn-microcloud-beta-3
  company.name: www.mldnjava.cn
  app.version: v-beta-3.5.2